final/urls.py
from django.urls import path

from . import views
app_name = 'final'

app_name = 'final'

urlpatterns = [
    path('',views.index,name = 'index')
        ]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('map/',include('final.urls')),
    path('sightings/',include('sightings.urls')),
]

sightings/urls.py
from django.urls import path

from . import views
app_name = 'sightings'

urlpatterns = [
        path('',views.show,name ='show'),
        path('add/',views.add_sightings,name = 'add'),
        path('stats/', views.stats,name = 'stats'),
        path('<Unique_Squirrel_ID>/',views.detail,name = 'detail'),
        ]

final/models.py
from django.db import models

class Location(models.Model):
    Latitude = models.FloatField()
    Longtitude = models.FloatField()
    Unique_Squirrel_ID = models.CharField(max_length = 100)
    
    AM = 'AM'
    PM = 'PM'
    OTHER = ''
    shift_choice = [
            (AM, 'AM'),
            (PM, 'PM'),
            (OTHER, '')
            ]
    Shift = models.CharField(
            max_length = 15,
            choices = shift_choice,
            default = OTHER,
            )
    
    Date = models.CharField(max_length = 100,default = '')
    
    ADULT = 'Adult'
    JUVENILE = 'Juvenile'
    age_choice = [
            (ADULT,'Adult'),
            (JUVENILE,'Juvenile'),
            (OTHER,''),
            ]
    Age = models.CharField(
        max_length=30,
        choices=age_choice,
        default=OTHER,
        blank=True,
    )

    GRAY = 'Gray'
    CINNAMON = 'Cinnamon'
    BLACK = 'Black'
    fur_choice = [
        (GRAY, 'Gray'),
        (CINNAMON, 'Cinnamon'),
        (BLACK, 'Black'),
        (OTHER, ''),
    ]

    Primary_Fur = models.CharField(
        max_length=30,
        choices=fur_choice,
        default=OTHER,
        blank=True,
    )

    GROUND = 'Ground'
    ABOVE = 'Above'
    location_choice = [
        (GROUND, 'Ground'),
        (ABOVE, 'Above'),
        (OTHER, ''),
    ]

    Location = models.CharField(
        max_length=30,
        choices=location_choice,
        default=OTHER,
        blank=True,
    )

    Specific_Location = models.CharField(max_length=100, blank=True)
    Running = models.BooleanField(null = True)
    Chasing = models.BooleanField(null = True)
    Climbing = models.BooleanField(null = True)
    Eating = models.BooleanField(null = True)
    Foraging = models.BooleanField(null = True)

    Other_Activities = models.CharField(max_length=100, blank=True)
    Kuks = models.BooleanField(null = True)
    Quaas = models.BooleanField(null = True)
    Moans = models.BooleanField(null = True)
    Tail_Flags = models.BooleanField(null = True)
    Tail_Twitches = models.BooleanField(null = True)
    Approaches = models.BooleanField(null = True)
    Indifferent = models.BooleanField(null = True)
    Runs_From = models.BooleanField(null = True)

    
    def __str__(self):
        return self.Unique_Squirrel_ID

sightings/models.py
from django.db import models

# Create your models here.

sightings/forms.py
from django.forms import ModelForm

from final.models import Location


class LocationForm(ModelForm):
    class Meta:
        model = Location
        fields = [
                'Latitude',
                'Longtitude',
                'Unique_Squirrel_ID',
                'Shift',
                'Date',
                'Age',
                ]

class AddForm(ModelForm):
    class Meta:
        model = Location
        fields = [
                'Latitude',
                'Longtitude',
                'Unique_Squirrel_ID',
                'Shift',
                'Date',
                'Age',
                ]

final/views.py
from django.shortcuts import render
from .models import Location
import random

def index(request):
    locations = Location.objects.all()
    locations_random = Location.objects.order_by('?')[:80]
    context = {
            'locations':locations_random,
            }

    return render(request,'final/index.html',context)

sightings/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse
from django.db.models import Count, Max, Q

from final.models import Location
from sightings.forms import LocationForm
from sightings.forms import AddForm

def show(request):
    locations = Location.objects.all()
    context = {
            'locations':locations
            }
    return render(request,'sightings/show.html',context)

def detail(request,Unique_Squirrel_ID):
    squirrel = Location.objects.get(Unique_Squirrel_ID = Unique_Squirrel_ID)
    #form= LocationForm(request.POST or None)
    if request.method == 'POST':
        form= LocationForm(request.POST,instance=squirrel)
        if form.is_valid():
            form.save()
            return redirect('sightings:show')

    form= LocationForm(instance=squirrel)
    context = {
           'form':form
            }
    return render(request, 'sightings/detail.html',context)


def add_sightings(request):
    addform = AddForm(request.POST)
    if request.method == 'POST':
        if addform.is_valid():
            addform.save()
            return redirect('sightings:show')
        else:
            return JsonResponse({'Errors':addform.errors}, status=400)
    
    context = {
            'addform': addform
            }
    return render(request, 'sightings/add_sightings.html',context)


def stats(request):
    Total_Sightings = Location.objects.aggregate(total_sightings=Count('Unique_Squirrel_ID'))
    Age_Count = Location.objects.values('Age').annotate(age_count=Count('Age'))
    Shift_Count = Location.objects.values('Shift').annotate(shift_count=Count('Shift'))
    Latest_Sighting = Location.objects.aggregate(latest_sighting=Max('Date'))
    Fur_Color_Count = Location.objects.values('Primary_Fur').annotate(fur_color_count=Count('Primary_Fur'))
    context = {
            'Total_Sightings': Total_Sightings,
            'Age_Count': Age_Count,
            'Latest_Sighting': Latest_Sighting,
            'Fur_Color_Count': Fur_Color_Count,
            'Shift_Count': Shift_Count,
            }
    return render(request, 'sightings/stats.html', context)

final/templates/final/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet"
          href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
            integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
            crossorigin=""></script>

    <style>
      html,body {
        height: 100%;
      }
    </style>
  </head>
  <body>
    <div id="map" class="container-fluid h-100"></div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Leaflet JS -->
    <script>
        var map_center = [
            40.782091,  // Latitude
            -73.964285  // Longitude
        ];
        var zoom_level = 14;
        var map = L.map('map').setView(map_center, zoom_level);
        L.tileLayer('https://{server}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            server: 'a',  // can be 'a', 'b', or 'c'
            // must leave attribution in!
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        }).addTo(map);

        <!-- L.Icon.Default.prototype.options.iconSize = 15; -->
        <!-- L.Icon.Default.prototype.options.iconAnchor = [0, 0]; -->
        <!-- L.Icon.Default.prototype.options.shadowSize = 15; -->
        <!-- L.Icon.Default.prototype.options.shadowAnchor = [0, 0]; -->	
        {% for l in locations %}
          var point_lat_lon = [{{ l.Latitude }}, {{ l.Longtitude }}];
          var marker = L.marker(point_lat_lon).addTo(map);
        {% endfor %}
    </script>
  </body>
</html>

sightings/templates/sightings/add_sightings.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Create a new sighting</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="{% url 'final:index' %}">Map</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'sightings:show' %}">Sightings </a>
          </li>
	   <li class="nav-item">
            <a class="nav-link" href="{% url 'sightings:add' %}">Add Sighting</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'sightings:stats' %}">Stats</a>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="container">

      <div class="starter-template">
	<h1>Bootstrap starter template</h1> 
	<p class="lead"> <strong>Create a new sighting.</strong></p>
      </div>
      
    </div>
       <div>
    <form  method="post">
        {% csrf_token %}
        {{ addform.as_p }}
        <input type="submit" value="Add Sighting">
       </form>

       </div>
     </main><!-- /.container -->

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    
  </body>
</html>

sightings/templates/sightings/detail.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="
sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="{% url 'final:index' %}">Map</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'sightings:show' %}">Sightings </a>
          </li>
	   <li class="nav-item">
            <a class="nav-link" href="{% url 'sightings:add' %}">Add Sighting</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'sightings:stats' %}">Stats</a>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="container">

      <div class="starter-template">
        <h1>Bootstrap starter template</h1>
	<strong><p class="lead"> Update the sightings below.</p></strong>
      </div>
      <div>
          <form  method="post">
              {% csrf_token %}
              {{ form.as_p }}
              <input type="submit" value="Submit">
          </form>
      </div>

    </main><!-- /.container -->


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

sightings/templates/sightings/show.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="{% url 'final:index' %}">Map</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'sightings:show' %}">Sightings </a>
          </li>
	   <li class="nav-item">
            <a class="nav-link" href="{% url 'sightings:add' %}">Add Sighting</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'sightings:stats' %}">Stats</a>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="container">

      <div class="starter-template">
	<h1>Bootstrap starter template</h1> 
	<strong><p class="lead"> Check the sightings below.</p></strong>
      </div>
      <div>
          {% for l in locations%}
          <li><a href="{% url 'sightings:detail' l.Unique_Squirrel_ID %}">{{l.Unique_Squirrel_ID}}</a></li>
          Date: {{l.Date}}
          {% endfor %}
      </div>

    </main><!-- /.container -->


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

sightings/templates/sightings/stats.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity=
"sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>General Statistics of the Squirrel Sightings.</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="{% url 'final:index' %}">Map</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-
controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'sightings:show' %}">Sightings </a>
          </li>
           <li class="nav-item">
            <a class="nav-link" href="{% url 'sightings:add' %}">Add Sighting</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'sightings:stats' %}">Stats</a>
          </li>
        </ul>
      </div>
    </nav>
    <main role="main" class="container">
      <div class="starter-template">
        <h1>Bootstrap starter template</h1>
        <p class="lead"><strong> General Statistics of the Squirrel Sightings.</strong></p>
      </div>


</div>
       <div>
        <div>
                <li>Total Number of Sightings: {{Total_Sightings.total_sightings}}</li>
        </div>
        <div>
		<li>Most Recent Sighting: {{Latest_Sighting.latest_sighting}} </li>
        </div>
        <div>
                {% for s in Shift_Count %}
		<li>Shift Count - {{s.Shift}}: {{s.shift_count}} </li>
                {% endfor %}
        </div>
        <div>
                {% for age in Age_Count %}
                <li>Age Count - {{age.Age}}: {{age.age_count}} </li>
                {% endfor %}
        </div>
        <div>
                {% for fur in Fur_Color_Count %}
		<li>Fur Color - {{fur.Primary_Fur}}: {{fur.fur_color_count}} </li>
                {% endfor %}
        </div>

       </div>
     </main><!-- /.container -->

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>


  </body>
</html>